### ISSUE TITLE
Renseigner le wiki - Sénégal

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-senegal#11]
Afin de cerner l'ensemble des éléments du système socio-fiscal sénégalais à mettre en oeuvre dans openfisca, il est utile de disposer d'une description sommaire des différentes composantes de ce système avec des liens vers des sources appropriées.

Il serait donc très utile de rassembler cette information dans le [wiki](https://github.com/openfisca/openfisca-senegal/wiki).

@Leocza  l'idéal serait que tu reportes brièvement dans le wiki les éléments de législation que tu as rassemblés. Puis dans un second mouvement, nous les mettrons sous forme de code openfisca étape par étape.

**Comment by benjello** [comment]
@Leocza : est-ce toi qui va te charger de cela ? Doit-on charger quelqu'un d'autre ?

**Comment by Leocza** [comment]
Je vais commencer, puis Akim devrait pouvoir me prêter main forte je pense

**Comment by Al-mouksit** [comment]
Hello, pas de problème Léo!

**Comment by benjello** [comment]
@Leocza @Mouksit : je ferme car cette "issue" est désormais imprécise.
